### ISSUE TITLE
Require document problem

### ISSUE THREAD

**Issue by todouu** [XZES40/CS-Capstone-Project#9] opened 2016-10-26 20:07 UTC
## For the overall-description file
1. Software interfaces is not complete, may be we need GUI tools, but what the tools are? 
2. Memory constraints
3. Operations  
4. Constraints, I write some of idea, but it's not complete.  
5. Apportioning of requirements

**Comment by pop** [comment] 2016-10-27 03:33
This is a duplicate of issue #8

**Closed as completed by pop** 2016-10-27 03:34 UTC
